name: Build and publish
description: Build and publish docker images to GHCR

inputs:
  image-name:
    description: Name of the image
    required: true
  build-args:
    description: List of args needed to build the image
    required: true
  github-token:
    description: GITHUB_TOKEN
    required: true

outputs:
  image-tag:
    description: "Image tag"
    value: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}

runs:
  using: composite
  steps:
    - 
      name: Setup BuildX
      uses: docker/setup-buildx-action@v3
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/${{ inputs.image-name }}
        flavor: |
          latest=false
        tags: |
          type=sha,format=long,prefix=,priority=300
          type=raw,value=latest,enable={{is_default_branch}},priority=200
          type=semver,pattern={{version}},priority=100
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build-args }}
