name: Deploy Development

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      build-args:
        required: true
        type: string

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Setup BuildX
      uses: docker/setup-buildx-action@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}/${{ inputs.image-name }}
        flavor: |
          latest=false
        tags: |
          type=sha,format=long,prefix=,priority=300
          type=raw,value=latest,enable={{is_default_branch}},priority=200
          type=semver,pattern={{version}},priority=100
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build-args }}
